site_name: Analyse des g√©nomes 2025
nav:
    - Accueil: index.md
    - 1. Petits ARN: srna.md
    - 2. RNAseq: rnaseq.md
    - 3. IGV: igv.md
    - 4. Ressources: ressources.md
    - 5. Annexes: annexes.md
theme: readthedocs
markdown_extensions:
    - admonition